version: "3.9"
services:
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: maker
      POSTGRES_USER: maker
      POSTGRES_DB: maker

volumes:
  pgdata: {}
